---
- name: make a build dir
  file: state=directory name=/root/grafana-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/grafana-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/grafana-dockerized/start.sh mode=0755

- name: build a Docker image for Grafana
  command: docker build -t gitinsky/grafana:0.1.6 --rm /root/grafana-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/grafana:latest --rm /root/grafana-dockerized
